import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs/internal/Observable';
import { throwError } from 'rxjs/internal/observable/throwError';
import { catchError, switchMap } from 'rxjs/operators';
import { of } from 'rxjs';

// Generated by https://quicktype.io

export interface Userlist {
    id:       number;
    fname:    string;
    mname:    string;
    lname:    string;
    position: string;
}


  @Injectable({
    providedIn: 'root'
  })
  export class AddUserService {
    constructor(private _httpClient: HttpClient){
    }

    addUser(data): Observable<any> {
        return this._httpClient.post<any>('/api/Add-Users', data);
    }


   

    postEventImage(id: number, file: File): Observable<any> {
      const formData: FormData = new FormData();
      formData.append('ImageFile', file, file.name);

      return this._httpClient.post<any>(
          `api/Upload/User-Profile/${id}`,
          formData
      );
    }




  }