import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs/internal/Observable';
import { throwError } from 'rxjs/internal/observable/throwError';
import { catchError, switchMap } from 'rxjs/operators';
import { of } from 'rxjs';



  // Generated by https://quicktype.io

export interface Visitors {
    id:               number;
    fname:            string;
    mname:            string;
    lname:            string;
    email:            string;
    purpose:          string;
    visitation_Sched: string;
    checkInDate:      string;
    checkInTime:      string;
    checkOutDate:     string;
    checkOutTime:     string;
}



  @Injectable({
    providedIn: 'root'
  })
  export class AppointmentVisitorService {
    constructor(private _httpClient: HttpClient){
    }

    addVisitor(data): Observable<any> {
        return this._httpClient.post<any>('/api/Add-Visitors', data);
    }


  }